spring:
  security:
    user:
      name: '${app.eureka-username}'
      password: '${app.eureka-password}'
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/