services:
  nginx:
    container_name: k-nginx
    image: 'nginx:1.25.1-alpine'
    restart: always
    volumes:
      - ./container/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
#    build:
#      context: .
#      dockerfile: ./nginx/Dockerfile
    depends_on:
      - api-gateway
  api-gateway:
    container_name: api-gateway
    restart: always
    hostname: apigateway
    ports:
      - 8090:8090
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    depends_on:
      - auth
  auth:
    container_name: auth
    restart: always
    hostname: auth-server
    ports:
      - 8091:8091
    build:
      context: .
      dockerfile: ./auth/Dockerfile
  mongodb:
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ./container/env/mong.env
    image: 'mongo:7.0.2'
    command: --timeStampFormat iso8601-local
    volumes:
      - ./container/mongo:/docker-entrypoint-initdb.d:ro
      - /local/data/mongo:/data/db
    ports:
      - '27020:27017'
