### GET request with environment variables
GET http://localhost:8080/main/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJzdWIiOiIxMDA2NzM3MTc4NTg1NjA4MTg2OTkiLCJleHAiOjE2OTIxNzc5NDUsImlhdCI6MTY5MjE3MDc0NSwiZW1haWwiOiJoYW5razIwQGdtYWlsLmNvbSJ9.mRT1H1CqJlAJ_BAFUuR-pv10SQuPEiHI-srIMCenB-eMiVA0JhSNRzqea7xJmf2KcSoAzXnV-wtwXh-9xslRXymxkhNMY092Ni8KpZlmDiqUALw-Bpcb3nSduup30z8Oo10T75yXPAdAduzl_rbdAY4FKaI2Ao078KA2tx6cLNRiUL62t1-h78ikEP9vGutdLslNpyo277Cnl8VQcnGzO6xXMmYzq7qkxaokK5kTNgS28jifmppunpq3ogJGzzD34Zd9GmSai6dc7u5jxvNf_hxji4A5e3LMO91UdYrHp_aBOC6qjPqSvKKIaSOgvBIoC2UHhrNeDv1JLXiLsYCJHA
