GET http://localhost:8080/me
Accept: application/json
x-auth: {"userId": "test", "roles": ["TEACHER"]}

###
GET http://localhost:8080/teacher/223334123
Accept: application/json
x-auth: {"userId": "test", "roles": ["TEACHER"]}

###
GET http://localhost:8080/teacher/561b3fbe-97ff-4168-a20d-d7679d2eead2
Accept: application/json
x-auth: {"userId": "test", "roles": ["TEACHER"]}
