GET http://localhost:8080/me
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqb2luZWQiOmZhbHNlLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3MDQ0MjQxNDksInVzZXJJZCI6IjI5NTkyMzc5MDEiLCJpYXQiOjE3MDQ0MTY5NDksImVtYWlsIjoiaGFua2syMEBuYXZlci5jb20iLCJvYXV0aFByb3ZpZGVyIjoia2FrYW8ifQ.bd4wWzyav9cH3zeGoLuAhLuNX95ecShHbdu-kk8g4R-_eQcmb8-xpXbZ0SIysxMtA9ZO40L0uvDWhLhsPhH2t1ynFtA7sYWdlBKhVtxif4WdUab233gScieCjDCHTSAeL0L9bxiq6bZgbSpm2Oyw8YdV8wEzkmtAIRBzTyQ38aPovFnmLKcE85O99-m6q20CO4uLPhcEtILVzCYJqf__DQJN3kzrLJPfK8DzzEpKZ87VKJcUaebGURPhITi7gWbY1nfivVl9kVqzFr4LC5zuCBmjzenk3tpyAae6qhNy0iDCcUP3HOxVEj8xAse0VAqfG4EhjE8Xrjb2s554_qxtIg
#x-auth: {"userId": "test", "authorities": ["TEACHER"]}

###
GET http://localhost:8080/teachers/223334123
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqb2luZWQiOmZhbHNlLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3MDQ0MjQxNDksInVzZXJJZCI6IjI5NTkyMzc5MDEiLCJpYXQiOjE3MDQ0MTY5NDksImVtYWlsIjoiaGFua2syMEBuYXZlci5jb20iLCJvYXV0aFByb3ZpZGVyIjoia2FrYW8ifQ.bd4wWzyav9cH3zeGoLuAhLuNX95ecShHbdu-kk8g4R-_eQcmb8-xpXbZ0SIysxMtA9ZO40L0uvDWhLhsPhH2t1ynFtA7sYWdlBKhVtxif4WdUab233gScieCjDCHTSAeL0L9bxiq6bZgbSpm2Oyw8YdV8wEzkmtAIRBzTyQ38aPovFnmLKcE85O99-m6q20CO4uLPhcEtILVzCYJqf__DQJN3kzrLJPfK8DzzEpKZ87VKJcUaebGURPhITi7gWbY1nfivVl9kVqzFr4LC5zuCBmjzenk3tpyAae6qhNy0iDCcUP3HOxVEj8xAse0VAqfG4EhjE8Xrjb2s554_qxtIg

