spring:
  application.name: api-gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      routes:
       #service
        - id: oauth-server
          uri: lb://member-service
          predicates:
           - Path=/oauth2/**,/login/**
        - id: oauth-server
          uri: lb://member-service
          predicates:
            - Path=/member-service/**
          filters:
            - StripPrefix=1
        - id: teacher
          uri: lb://institution-service
          predicates:
            - Path=/institution-service/**
          filters:
            - StripPrefix=1
logging:
  level:
    root: debug
---
spring.config.activate.on-profile: docker
spring.cloud.config.uri: http://config-server
