spring:
  application.name: member-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      allow-override: false
logging:
  level:
    root: debug
---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      uri: http://config-server
